import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import PageHeader from '../components/ui/PageHeader.jsx';

// TODO-CONTENT: placeholder legal policy — must be reviewed by
// qualified legal counsel before the site or platform goes live.
// This draft addresses common B2B SaaS/IoT data-handling concerns
// but is not a substitute for professional legal advice.

const SECTIONS = [
  {
    id: 'scope',
    title: 'Scope of this policy',
    content: (
      <>
        <p>
          This Privacy Policy describes how Device-Nova, Inc. ("Device-Nova," "we," "our," or "us")
          collects, uses, stores, and shares information when you visit our website, request a demo,
          or deploy the Device-Nova edge intelligence platform (the "Platform"). It applies to
          website visitors, prospective customers, and organizations that enter into a service
          agreement with us.
        </p>
        <p>
          Separate data processing terms in your Enterprise Agreement govern the handling of
          operational telemetry, device data, and model outputs generated by the Platform in a
          production deployment. Where those terms conflict with this policy, the Enterprise
          Agreement controls.
        </p>
      </>
    ),
  },
  {
    id: 'collection',
    title: 'Information we collect',
    subsections: [
      {
        title: 'Information you provide directly',
        content:
          'When you fill out a contact form, request a demo, subscribe to our newsletter, or communicate with our team, we collect your name, email address, company name, phone number, and any details you share about your deployment environment or evaluation criteria.',
      },
      {
        title: 'Website usage information',
        content:
          'We collect standard web analytics data — pages visited, referral source, browser type, device type, and interaction timestamps — via first-party cookies and similar technologies. You can control cookie preferences through your browser settings.',
      },
      {
        title: 'Platform account information',
        content:
          'When you create a Platform account, we collect your name, work email, role, and organization details. This information is used for authentication, license management, and product communications related to your deployment.',
      },
      {
        title: 'Operational telemetry (production deployments)',
        content:
          'The Platform processes device-generated telemetry, sensor readings, and inference results at the edge. By default, this data remains on your infrastructure. Cloud sync, if enabled by your organization, transmits aggregated or sampled data under terms defined in your Enterprise Agreement. Device-Nova does not use customer telemetry data for model training or any purpose outside the scope of your agreement.',
      },
    ],
  },
  {
    id: 'use',
    title: 'How we use information',
    content: (
      <>
        <p>We use the information we collect for the following purposes:</p>
        <ul className="space-y-2">
          <li><strong>Service delivery.</strong> To operate, maintain, and improve the Platform, including license management, authentication, and technical support.</li>
          <li><strong>Communications.</strong> To respond to inquiries, schedule demos, send product updates, and share relevant documentation. Marketing communications include an opt-out mechanism.</li>
          <li><strong>Security and compliance.</strong> To detect and prevent unauthorized access, abuse, or violation of our Terms of Service, and to meet regulatory obligations applicable to our operations.</li>
          <li><strong>Product improvement.</strong> To analyze aggregated, de-identified usage patterns for the purpose of improving Platform performance, reliability, and feature design. This analysis never involves customer telemetry data.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'sharing',
    title: 'When we share information',
    content: (
      <>
        <p>Device-Nova does not sell personal information. We may share information in the following circumstances:</p>
        <ul className="space-y-2">
          <li><strong>Service providers.</strong> We engage third-party vendors for cloud hosting, analytics, email delivery, and customer relationship management. These providers are bound by data processing agreements that prohibit use of your data for any purpose other than the services they perform for us.</li>
          <li><strong>Legal obligations.</strong> We may disclose information if required by law, legal process, or governmental request, or to protect the rights, property, or safety of Device-Nova, our customers, or others.</li>
          <li><strong>Business transfers.</strong> In the event of a merger, acquisition, or sale of assets, personal information may be transferred as part of that transaction, subject to confidentiality obligations consistent with this policy.</li>
          <li><strong>With your consent.</strong> We share information for any other purpose when we have your explicit consent.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'retention',
    title: 'Data retention',
    content: (
      <>
        <p>
          Contact and account information is retained for the duration of our relationship with you
          or your organization, plus a reasonable period thereafter to comply with legal obligations,
          resolve disputes, and enforce agreements. Operational telemetry processed at the edge is
          retained per your organization's configuration and retention policy — Device-Nova does not
          retain copies of customer telemetry on our infrastructure unless cloud sync has been
          explicitly configured and the applicable Enterprise Agreement specifies a retention schedule.
        </p>
      </>
    ),
  },
  {
    id: 'security',
    title: 'Security practices',
    content: (
      <>
        <p>
          We apply industry-standard security controls to protect information in our custody,
          including encryption in transit (TLS 1.3) and at rest (AES-256), role-based access
          control, multi-factor authentication for internal systems, and routine third-party
          penetration testing. The Platform's edge runtime is designed to operate without
          transmitting sensitive data over the network at any point in the inference critical path.
        </p>
        <p>
          No system is impenetrable. Device-Nova cannot guarantee absolute security of information
          stored or transmitted through our services, and we encourage customers to implement
          additional security measures appropriate to their operational context.
        </p>
      </>
    ),
  },
  {
    id: 'rights',
    title: 'Your rights and choices',
    content: (
      <>
        <p>
          Depending on your jurisdiction, you may have the right to access, correct, delete, or
          port the personal information we hold about you. You may also have the right to restrict
          or object to certain processing activities. To exercise these rights, contact us at
          privacy@device-nova.com. We will respond within the timeframe required by applicable law.
        </p>
        <p>
          If you are based in the European Economic Area, the United Kingdom, or Switzerland, you
          also have the right to lodge a complaint with your local data protection supervisory
          authority.
        </p>
      </>
    ),
  },
  {
    id: 'international',
    title: 'International data transfers',
    content: (
      <>
        <p>
          Device-Nova is based in the United States and processes data in accordance with US law.
          If you are located outside the US, information we collect may be transferred to, stored,
          and processed in the US or other jurisdictions where our service providers operate. We
          rely on Standard Contractual Clauses, adequacy decisions, or other lawful transfer
          mechanisms as required by applicable data protection law.
        </p>
      </>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to this policy',
    content: (
      <>
        <p>
          We may update this Privacy Policy from time to time. Material changes will be communicated
          via email to the primary contact for active enterprise customers and via a notice on our
          website at least 30 days before the changes take effect.
        </p>
      </>
    ),
  },
  {
    id: 'contact',
    title: 'Contact',
    content: (
      <>
        <p>
          Questions, concerns, or data subject requests should be directed to:
        </p>
        <p className="text-primary">
          Device-Nova, Inc.<br />
          Attn: Privacy<br />
          privacy@device-nova.com
        </p>
      </>
    ),
  },
];

function flattenSections(sections) {
  const result = [];
  sections.forEach((s) => {
    result.push({ id: s.id, title: s.title, depth: 0 });
    if (s.subsections) {
      s.subsections.forEach((sub) => {
        result.push({ id: sub.id || sub.title.toLowerCase().replace(/\s+/g, '-'), title: sub.title, depth: 1 });
      });
    }
  });
  return result;
}

function useActiveSection(sectionIds) {
  const [activeId, setActiveId] = useState(sectionIds[0]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio);
        if (visible.length > 0) {
          setActiveId(visible[0].target.id);
        }
      },
      { rootMargin: '-20% 0px -60% 0px', threshold: [0, 0.25, 0.5] }
    );

    sectionIds.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, [sectionIds]);

  return activeId;
}

export default function Privacy() {
  const flatSections = flattenSections(SECTIONS);
  const sectionIds = flatSections.map((s) => s.id);
  const activeId = useActiveSection(sectionIds);

  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Privacy Policy"
        description="How Device-Nova handles data across our website, platform, and edge-deployed infrastructure."
      />
      <p className="container-base text-center mb-12 -mt-6">
        <span className="font-mono text-xs text-muted/60">Last updated June 2026</span>
      </p>

      <section className="container-base pb-32">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-10">
          {/* Table of contents — sticky sidebar */}
          <nav
            className="lg:col-span-1 lg:sticky lg:top-32 lg:self-start"
            aria-label="Table of contents"
          >
            <ul className="space-y-1.5">
              {flatSections.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className={`block text-sm transition-colors duration-300 rounded-sm focus-visible:ring-2 focus-visible:ring-cyan ${
                      s.depth === 1 ? 'pl-4' : ''
                    } ${
                      activeId === s.id
                        ? 'text-cyan font-medium'
                        : 'text-muted hover:text-primary'
                    }`}
                  >
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {/* Content — reading column */}
          <div className="lg:col-span-3 max-w-3xl space-y-10">
            {SECTIONS.map((section) => (
              <div key={section.id} id={section.id} className="scroll-mt-28">
                <h2 className="font-display text-2xl font-semibold text-primary mb-4">{section.title}</h2>
                {section.subsections ? (
                  <div className="space-y-6">
                    {section.subsections.map((sub, i) => (
                      <div key={i}>
                        <h3 className="font-display text-lg font-semibold text-primary mb-2">{sub.title}</h3>
                        <p className="text-muted leading-relaxed">{sub.content}</p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="prose-custom space-y-4 text-muted leading-relaxed">
                    {section.content}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}